# Generated by Django 5.0.1 on 2024-01-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available_posts',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
